Numerical Python (numpy): arrays
================================

Introduzione a Numpy 
------------------

La librery NumPy (NUMerical PYthon) fornisce

-   un nuovo tipo di struttura dei dati chiamata `array`s che permette

-   di eseguire in modo efficiente operazioni su vettori e matrici. Fornisce inoltre

-   diverse  operazioni legate all'algebra lineare (come risolvere sistemi di equazioni lineari, calcolo di autovettori e autovalori).

## L'array

NumPy introduce un nuovo tipo di dati detto “`array`”. Un array *sembra* molto simile a una lista ma un array può contenere solo elementi di un singolo tipo (mentre una lista può contenere oggetti di tipo diverso). Questo significa che gli array possono essere scritti in memoria in modo più efficiente. Gli array sono la struttura di dati migliore per i calcoli numerici in cui spesso si ha a che fare con vettori e matrici di tipo omogeneo.

Vettori, matrici bidimensionali e matrici con più di due indici sono tutti chiamati “arrays” in NumPy.

### Vettor1 (1d-arrays)

La struttura dati data che useremo più spesso è il vettore. Qualche esempio di come crearne uno:

-   Conversione di una lista (o tuple) in un array usando <span>`numpy.array`</span>:

In [2]:
import numpy as np
x = np.array([0, 0.5, 1, 1.5])
print(x)

[0.  0.5 1.  1.5]


In [ ]:
type(x)

In [ ]:
type([0, 0.5, 1, 1.5])

In [ ]:
x

- Creazione di un vettore usando "arange":

In [ ]:
x = np.arange(0, 2, 0.5)
print(x)

-   Creazione di un vettore di zeri, di uno

In [ ]:
x = np.zeros(4)
print(x)
y = np.ones(10)
print(y)

#### I comandi linspace() e logspace()

In Numpy esiste il comando `linspace(x0, x1, n)`, che genera una lista di `n` elementi equidistanti fra `x0` e `x1` (inclusi). Il comando `logspace(x0, x1, n)` genera una lista di `n` elementi equidistanti, in scala logaritmica, fra `10\*\*x0` e `10\*\*x1`; è utile per fare plot logaritmici come vedremo in 08_plots. Alcuni esempi:

In [ ]:
np.linspace(0,10,1001)

In [ ]:
np.linspace(-1,1,21)

Ricordate che i primi due argomenti di logspace sono i logaritmi in base 10 del punto iniziale e di quello finale.

In [ ]:
np.logspace(1,4,4)
#np.logspace(1.7,4.4,40)

#### Come scegliere o modificare il `tipo` di dati di un array

Quando viene creato un array è possibile specificare il tipo di dati che contiene. I tipi possibili sono: 'float', 'complex', 'int', 'bool', 'str' and 'object'. Un controllo più fine si può avere usando espressioni come 'float32', 'float64', 'int8', 'int16' oppure 'int32'; l'intero specifica il numero di bytes. 

In [ ]:
array_f = np.array([1,2,3], dtype='float')
array_i = np.array([1,2,3], dtype='int16')

In [ ]:
array_f

In [ ]:
array_i

In [ ]:
np.array([1,2,123456790],dtype='int32')

Il tipo di un array può essere modificato con il metodo astype

In [ ]:
array_f.astype('complex')

### Operazioni su array

- Una volta che l'array esiste, possiamo definire e recuperare il valore degli elementi. Per esempio:

In [ ]:
x = np.zeros(4)
x[0] = 3.4
x[2] = 4
print(x)

- I metodi di slicing per le stringhe/liste/ntuple si possono applicare anche agli array:

In [ ]:
print(x[0])
print(x[0:-1])

- La lunghezza di un array si ottiene con `len`

In [ ]:
len(x)

- Come estrarre più elementi da un array

In [ ]:
x = np.arange(10)
x

In [ ]:
x1 = [x[2],x[3],x[5]]
print(x1)
type(x1)

Per ottenere un array:

In [ ]:
x1 = np.array(x1)
print(x1)
type(x1)

- Come estrarre più elementi da un array usando un array di indici

In [ ]:
ind = [2,3,5]
x[ind]       # Restituisce un array

- Quando abbiamo un array possiamo eseguire operazioni su ogni elementi con un solo comando.<BR>
__È sbagliato e dannoso iterare esplicitamente sulle componenti.__

In [ ]:
x = np.arange(0, 2, 0.5)
print(x)

In [ ]:
print(x + 10)
print(x*33)

In [ ]:
print(x ** 2)
print(np.sin(x))

In [ ]:
y1 = np.array([1.,2.,3.])
y2 = np.array([-1.,-10,+100])
y1+y2

Il modo migliore di applicare una funzione in numpy è definire l'array dei punti in cui la funzione deve essere calcolata e poi applicare la funzione all'array.<BR>
Esempio: per calcolare i valori del polinomio y = 3\* x\*\*3 - 2\*x\*\*2 + 1 fra -5 e 5:

In [ ]:
def myfunc(arr):
    return 3*arr**3 -2*arr*arr +1

x = np.linspace(-5,5,101)
print(x)
res = myfunc(x)
res

check:

In [ ]:
3*(-4.9)**3 -2*(-4.9)**2 +1.

- Come estrarre da un array gli elementi che soddisfano una condizione data. Nell'esempio gli elementi dispari. 

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

oppure, con più flessibilità sul modo di imporre le condizioni:

In [ ]:
np.array([x for x in arr if x% 2 == 1])

- Come sostituire in un array gli elementi che soddisfano una condizione data con un valore fisso.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1
arr

- Come ottenere lo stesso risultato senza modificare l'array iniziale.

In [ ]:
#help(np.where)

In [ ]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

In [ ]:
#help(np.where)

- Come estrarre gli elementi "unici" e il numero di volte in cui compaiono in un array:

In [ ]:
uniqs, counts = np.unique(out, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

In [ ]:
uniqs2 = np.unique(out)
uniqs2

In [ ]:
#help(np.unique)

- Come selezionare gli elementi comuni fra due array.

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

- Come eliminare da un array `a` tutti gli elementi che compaiono anche in `b`.

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

In [ ]:
np.asarray(a == b)

In [ ]:
np.asarray(a == b).nonzero()     # restituisce gli indici degli elementi non nulli cioè di quelli non False

In [ ]:
c = np.array([-1,0,33,1,0])

In [ ]:
#help(np.asarray)

In [ ]:
#help(np.nonzero)

- Come estrarre da un array gli elementi in un intervallo dato.

In [ ]:
a = np.arange(15)
a

In [ ]:
# Metodo 1
index = np.where((a >= 5) & (a <= 10))
print(a[index])

In [ ]:
# Metodo 2:
index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])

# Metodo 3:
a[(a >= 5) & (a <= 10)]

<img src="../Humour/hip-hip-array.jpg" width="500" align="center"/>

### Convertire da  array a lista o tuple

Per convertire un array in una lista o una si possono usare le funzioni python standard <span>`list(s0)`</span> e <span>`tuple(s0)`</span> che accettano una sequenza <span>`s0`</span> come input e ritornano rispettivamente  una lista e una ntupla:

In [ ]:
a = np.array([1, 4, 10])
a

In [ ]:
list(a)

In [ ]:
tuple(a)

## Matrici (2d-arrays)

Ecco due modi per creare un array a due dimensioni:

-   Convertendo una lista di liste (o tuples) in un array:

In [ ]:
x = np.array([
    [1, 2, 3], [4, 5, 6]
])
x

-   Usare il metodo  <span>`zeros`</span> per creare una matrice di zeri. Un esempio con 5 righe e 4 colonne:

In [ ]:
x = np.zeros((5, 4))
x

La "forma" di una matrice può essere trovata con il comando `shape` (in questo caso ci sono 2 righe e 3 colonne):

In [ ]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x.shape

I singoli elementi possono essere recuperati con la sintassi seguente:

In [7]:
x=np.array([[1, 2, 3], [4, 5, 6]])
x[0, 0] 

1

In [8]:
x[0, 1]

2

In [ ]:
x[0, 2]

In [9]:
x[1, 0]

4

In [ ]:
x[:, 0]

In [ ]:
x[0,:]

- Un esempio su come sostituire elementi multipli in una matrice<BR>
Supponiamo di voler creare la matrice:
 $$A = \begin{bmatrix} -2 & 0 & 0 \\ 0 & 5 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$
 Un metodo è il seguente:  

In [ ]:
A = np.zeros((3,3))
print(A)
vec = np.array([-2,5,1])
indeces = np.array([0,1,2])
A[indeces[:],indeces[:]] = vec[:]
A

### Operazioni standard in Algebra Lineare

#### Vettori

Prodotto interno, esterno, vettoriale

In [3]:
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]


In [4]:
print("Inner product of x and y:")
print(np.inner(x, y))

Inner product of x and y:
10.0


In [6]:
print("Outer product of x and y:")
print(np.outer(x, y))

Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]


In [5]:
print("Cross product of x and y:")
print(np.cross(x, y))

Cross product of x and y:
[ 4. -1. -6.]


#### Moltiplicazione fra matrici

Due arrays possono essere moltiplicato nel senso usuale dell'algebra lineare usando <span>`numpy.dot`</span>. Ecco un esempio:

In [ ]:
import numpy as np
import numpy.random       
A = numpy.random.rand(5, 5)    # genera matrice random 5 by 5 
x = numpy.random.rand(5)       # genera un vettore di 5 elementi
print(A)

In [ ]:
print(x)

In [ ]:
b=np.dot(A, x)                  # multiplica la matrice A per il vettore x 
print(b)

#### Risolvere un sistema di  equazioni lineari

Per risolvere un sistema di  equazioni lineari `A*x = b`, dato in forma matriciale (cioè `A` è una matrice e `x` e `b` sono vettori, con `A` e `b` noti), possiamo usare la libreria di algebra lineare <span>`linalg`</span> di <span>`numpy`</span>:

In [ ]:
import numpy.linalg as LA
x = LA.solve(A, b)
x

check:

In [ ]:
print(np.dot(A,x))
print(b)

#### Determinante e traccia

In [ ]:
X = np.array([[1, 2], [4, 5]])

In [ ]:
LA.det(X)

In [ ]:
np.trace(X)

In [ ]:
#help(np.linalg)

#### Calcolare autovettori e autovalori (eigenvector e eigenvalue)

Ecco un piccolo esempio che calcola gli autovettori e autovalori di una matrice con il comando <span>`eig`</span>:

In [ ]:
import numpy.linalg as LA
import numpy as np

R = np.array([[1,2,3], [1,0,1], [0,1,2]])

In [ ]:
LA.det(R)

In [ ]:
evalues, evectors = LA.eig(R)

In [ ]:
print(evalues)

Controlliamo se il prodotto degli autovalori è uguale al determinante:

In [ ]:
np.prod(evalues)

In [ ]:
print(evectors)

**Attenzione:** gli autovettori sono disposti sulle **colonne**.<BR>
    Verifica:

In [ ]:
A1=evectors[:,0]
print(A1)

In [ ]:
print(np.dot(R,A1))

In [ ]:
print(evalues[0]*A1)

Ciascuno di questi comandi fornisce la propria documentazione. Per esempio, <span>`help(LA.eig)`</span> fornisce dettagli sulla funzione che calcola autovettori e autovalori (Avendo importato `numpy.linalg` come `LA`).

### Come vettorializzare una funzione

Per avere programmi veloci è necessario evitare di ciclare sugli elementi di vettori e matrici usando invece algoritmi vettorializzati. Il primo passo per convertire un algoritmo scalare in un algoritmo vettorializzato è costruire delle funzioni che accettino input vettoriali.

In [ ]:
def Theta(x):
    """
    Implemenazione scalare della funzione a gradino di Heaviside.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

Per ottenere una versione vettorializzata di Theta si può utilizzare la  funzione  di Numpy `vectorize`. In molti  casi riesce a vettorializzare automaticamente una funzione:

In [ ]:
Theta_vec = np.vectorize(Theta)

In [ ]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

### Fit polinomiale di una curva

Assumiamo di avere dei dati x-y che vogliamo interpolare con una curva minimizzando la deviazione quadratica del fit rispetto ai dati).

Numpy fornisce la  funzione <span>`polyfit(x,y,n)`</span> che prende la lista <span>`x`</span> dei valori della coordinata x dei dati, la lista <span>`y`</span> dei valori della coordinata y degli stessi dati e l'ordine del polinomio con cui si vuole interpolare i dati quanto meglio è possibile nel senso dei minimi quadrati.

In [ ]:
import numpy

# dimostrazione di interpolazione polinomiale: xdata and ydata sono i dati di input
xdata = numpy.array([0.0 , 1.0 , 2.0 , 3.0 , 4.0 , 5.0])
ydata = numpy.array([0.0 , 0.8 , 0.9 , 0.1 , -0.8 , -1.0])
# fittiamo con un polinomio cubico (ordine = 3)
z = numpy.polyfit(xdata, ydata, 3)
# z è un array di coefficienti , iniziando da quello di grado più elevato:
#                 X^3            X^2          X             0
# z = array ([ 0.08703704 , -0.81349206 , 1.69312169 , -0.03968254])
# È conveniente usare l'oggetto ‘poly1d‘ per maneggiare polinomi:
p = numpy.poly1d(z) # crea un polinomio p dai coefficienti
                    # e p può essere valutato per qualunque x.

# Il grafico
xs = [0.1 * i for i in range (50)]
ys = [p (x) for x in xs]   # valuta p(x) per tutti gli x nella lista xs

import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(xs,ys, label='fitted curve')
ax.scatter(xdata,ydata, marker='o', c='r')


Il grafico mostra i dati e la curva interpolante (linea solida).

### Ulteriori esempi per numpy …

…si possono trovare in: <http://www.scipy.org/Numpy_Example_List>